In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")

Libraries imported successfully!

In [ ]:
file_path = r"C:\Users\ankit\Variance-full-backup\The_SEERA_Dataset\The SEERA Dataset\Dataset Files\SEERA dataset original raw data.xlsx"

df = pd.read_excel(
    file_path,
    sheet_name="General Information",
    header=1
)

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

Dataset loaded successfully!
Dataset shape: (120, 20)

In [22]:
# Display first 5 rows
display(df.head())

# Display last 5 rows
display(df.tail())

# Display all column names
print("Column names:")
for col in df.columns:
    print(col)

# Display dataset dimensions
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

,Unnamed: 0,Contract Date,Contract software delivery date,Actual software development start date,Year of project (Main),Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Contract price,Actual incurred costs,ActualEffort,% project gain (loss) (Main),Unnamed: 17,Unnamed: 18,projID
0,1,?,?,00/2015,2015,1,1,1,16,7,13,2.0,3.0,?,?,3.0,?,1,7,1
1,2,05/2016,05/2016,05/2016,2016,25,5,1,2,1,2,2.0,3.0,?,?,3.0,?,1,3,2
2,3,06/2008,03/2009,09/2008,2008,2,5,3,2,2,3,3.0,5.0,40000,40000,5.0,0,1,3,3
3,4,06/2010,01/2010,06/2009,2009,42,4,2,3,2,4,6.0,6.0,1500000,1750000,6.0,-0.166667,1,7,4
4,5,02/2016,2/1/2018,02/2016,2016,42,4,2,3,2,4,12.0,24.0,9000000000,10570000000,24.0,-0.174444,1,7,5

,Unnamed: 0,Contract Date,Contract software delivery date,Actual software development start date,Year of project (Main),Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Contract price,Actual incurred costs,ActualEffort,% project gain (loss) (Main),Unnamed: 17,Unnamed: 18,projID
115,116,03/2018,06/2018,01/2018,2018,38,1,2,16,1,13,2.0,3.0,?,?,3.0,?,4,7,120
116,117,00/1998,00/1999,00/1998,1998,4,4,1,3,3,3,6.0,18.0,100000,100000,18.0,0,1,1,121
117,118,?,?,01/2006,2006,14,2,2,16,6,13,2.0,5.0,?,?,5.0,?,1,5,125
118,119,04/2016,08/2016,?,2016,43,6,1,16,11,13,3.0,12.0,?,?,12.0,?,2,7,126
119,120,00/2016,00/2016,00/2016,2016,14,2,4,16,4,4,12.0,36.0,400000,1000000,36.0,-1.5,1,7,127

Column names:
Unnamed: 0
Contract Date
Contract software delivery date
Actual software development start date
Year of project (Main)
Unnamed: 5
Unnamed: 6
Unnamed: 7
Unnamed: 8
Unnamed: 9
Unnamed: 10
Unnamed: 11
Unnamed: 12
Contract price
Actual incurred costs
ActualEffort
% project gain (loss) (Main)
Unnamed: 17
Unnamed: 18
projID
Rows: 120
Columns: 20

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 20 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Unnamed: 0                              120 non-null    int64
 1   Contract Date                           120 non-null    object
 2   Contract software delivery date         120 non-null    object
 3   Actual software development start date  120 non-null    object
 4   Year of project (Main)                  120 non-null    int64
 5   Unnamed: 5                              120 non-null    int64
 6   Unnamed: 6                              120 non-null    int64
 7   Unnamed: 7                              120 non-null    int64
 8   Unnamed: 8                              120 non-null    int64
 9   Unnamed: 9                              120 non-null    int64
 10  Unnamed: 10                             120 non-null    int64
 11  Unnamed: 11                             120 non-null    float64
 12  Unnamed: 12                             120 non-null    float64
 13  Contract price                          120 non-null    object
 14  Actual incurred costs                   120 non-null    object
 15  ActualEffort                            120 non-null    float64
 16  % project gain (loss) (Main)            103 non-null    object
 17  Unnamed: 17                             120 non-null    int64
 18  Unnamed: 18                             120 non-null    int64
 19  projID                                  120 non-null    int64
dtypes: float64(3), int64(11), object(6)
memory usage: 18.9+ KB

In [24]:
# Count missing values in each column
missing_values = df.isnull().sum()

missing_table = pd.DataFrame({
    "Column": df.columns,
    "Missing_Count": missing_values.values,
    "Missing_Percentage": (
        missing_values.values / len(df) * 100
    ).round(2)
})

display(
    missing_table[
        missing_table["Missing_Count"] > 0
    ].sort_values("Missing_Count", ascending=False)
)

                          Column  Missing_Count  Missing_Percentage
16  % project gain (loss) (Main)             17               14.17

In [25]:
for col in df.select_dtypes(include="object").columns:
    print(
        col,
        df[col].astype(str).str.strip().isin(
            ["?", "-", "NA", "N/A", "nan", ""]
        ).sum()
    )

Contract Date 13
Contract software delivery date  14
Actual software development start date 8
Contract price  39
Actual incurred costs  39
% project gain (loss) (Main) 56